name: Deploy with Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2